name: run-tests

on:
  push:
    branches: [ 1.x, 2.x ]
  pull_request:
    branches: [ 1.x, 2.x ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '8.0'
          extensions: mbstring, dom, fileinfo
          coverage: xdebug #optional
      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.1.0
        with:
          # Redis version to use
          redis-version: 6 # optional, default is latest, was 5
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: 55a033428e7f980c68f3fe5e8f335098915f318d06843848ad2070fef53e331e
        with:
          coverageCommand: vendor/bin/pest --coverage --min=85
          debug: false
